name: igorcurriculum
description: "The online Curriculum of on the 5 percent best freelancers of Upwork. List of career achievements, employment history, open source projects and other abilities." 

publish_to: 'none'  
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0' 

dependencies:
  flutter:
    sdk: flutter
  lottie: ^2.7.0
  google_fonts: ^6.1.0
  image_network: ^2.5.4+1
  url_launcher: ^6.2.2
  provider: ^6.1.1
  flutter_animate: ^4.3.0
  enchanted_collection: ^1.1.2
  responsive_framework: 1.1.1
  rename_app:
  cupertino_icons: ^1.0.2 
  firebase_core: ^2.24.2
  firebase_analytics: ^10.8.0
  firebase_crashlytics: 3.4.9
  dart_debouncer: 
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1" 
  flutter_lints: ^2.0.0 

flutter_launcher_icons: 
  image_path: "art/flutter_bird_icon.png" 
  web:
    generate: true
    image_path: "art/flutter_bird_icon.png"

flutter: 
  uses-material-design: true 

  assets:
    - art/
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
